### ISSUE TITLE
Library in bower and in the plunker is not synchronized 

### ISSUE THREAD

**Issue by burakkilic** [BuffCoder/angular-currency#7]
Hi;

First I installed the library from bower. But it was working wrong. It was updating the model with currency symbol like in the photo.

![screen shot 2016-04-13 at 15 26 58](https://cloud.githubusercontent.com/assets/123382/14493230/05cbf81a-018d-11e6-899c-aecf315851a9.png)

But when I used the code in plunker, it was ok.

What is wrong?

**Comment by majster** [comment]
problem is that in plunker, code is:
```
elem.on('change', function () {
                    scope.$applyAsync(function () {
                        controller.$setViewValue(elem.autoNumeric('get'));
                    });
                });
```

on directive (https://github.com/BuffCoder/angular-currency/blob/master/angular-currency.js) is : 
```
elem.on('keypress', function () {
                    scope.$apply(function () {
                        controller.$setViewValue(elem.autoNumeric('get'));
                    });
                });
```

One works, but only after change event is triggered. Other is working with every 'keyup' event, but on 'change' event autoNumeric overrides value.

So what I did, was use both blocks of code in directive.

**Comment by BuffCoder** [comment]
Thanks for answering this @majster.  I haven't been too active with Angular in the last few months.

I noticed there is a [PR](https://github.com/BuffCoder/angular-currency/pull/9/files) for changing it from `keypress` to `change`.  Are you saying it should actually have both?  If so, mind creating a PR for that and I'll merge it in ASAP.

**Comment by BuffCoder** [comment]
#10 was merged in, and I updated the README and NPM packages so closing this.

Thanks guys.
